doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            ProductIdType: App\Catalog\Infrastructure\Persistence\Doctrine\Types\ProductIdType
            MoneyType: App\Catalog\Infrastructure\Persistence\Doctrine\Types\MoneyType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                prefix: 'App\Catalog\Domain'
                dir: '%kernel.project_dir%/src/Catalog/Infrastructure/Persistence/Doctrine/Mapping'
