framework:
    messenger:
        transports:

        routing:

        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction

            query.bus: ~
