framework:
    messenger:
        transports:

        routing:

        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - 'App\Common\Infrastructure\Messenger\Middleware\CommandValidationMiddleware'
                    - doctrine_transaction

            query.bus:
                middleware:
                    - 'App\Common\Infrastructure\Messenger\Middleware\CommandValidationMiddleware'
